
services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda_exercice2
    ports:
      - "9092:9092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - redpanda
      - start
      - --kafka-addr
      - 0.0.0.0:9092
      - --advertise-kafka-addr
      - redpanda:9092
      - --node-id
      - "0"

  init-redpanda:
    image: redpandadata/redpanda:v24.1.1
    container_name: init_redpanda
    depends_on:
      redpanda:
        condition: service_healthy
    entrypoint: /bin/bash
    command:
      - -c
      - sleep 5 && rpk topic create client_tickets --brokers redpanda:9092 --partitions 3 --replicas 1 || true

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: ticket_producer
    depends_on:
      init-redpanda:
        condition: service_completed_successfully
    env_file: .env
    environment:
      - REDPANDA_BROKER_LOCAL=redpanda:9092
    volumes:
      - ./data/output:/data/output
    restart: unless-stopped

  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile
    container_name: ticket_processor
    depends_on:
      init-redpanda:
        condition: service_completed_successfully
    env_file: .env
    environment:
      - REDPANDA_BROKER_LOCAL=redpanda:9092
    volumes:
      - ./data/output:/data/output
    restart: unless-stopped

volumes:
  redpanda_data:
